name: Sync Results
on:
  push:
    branches:
      - main

jobs:
  repoqa-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r ./results/repoqa/requirements.txt
      - name: Sync RepoQa Results
        run: |
          python results/repoqa/fetch_results.py
      - name: Commit changes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add results/repoqa/COMBINED-RESULTS.json
          git commit -m "Sync RepoQA Results"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="repoqa-sync-$(date +'%Y%m%d')"
          git checkout -b "$BRANCH_NAME"
          git push -u origin "$BRANCH_NAME"
      - name: Create Pull Request
        uses: actions/create-pull-request@v2
        with:
          branch: ${{ steps.push-changes.outputs.BRANCH_NAME }}
          title: "[Sync Bot] sync repoqa results"
          body: "Automatically updated RepoQA results"
          base: main
          
  evalperf-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Sync EvalPerf Results
        run: |
          python results/evalperf/stats.py
      - name: Commit changes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add results/evalperf/COMBINED-RESULTS.json
          git commit -m "Sync RepoQA Results"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="repoqa-sync-$(date +'%Y%m%d')"
          git checkout -b "$BRANCH_NAME"
          git push -u origin "$BRANCH_NAME"
      - name: Create Pull Request
        uses: actions/create-pull-request@v2
        with:
          branch: ${{ steps.push-changes.outputs.BRANCH_NAME }}
          title: "[Sync Bot] sync repoqa results"
          body: "Automatically updated RepoQA results"
          base: main
