name: Sync Results
on:
  push:
    branches:
      - main

jobs:
  evalperf-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Sync EvalPerf Results
        run: |
          python results/evalperf/stats.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ steps.push-changes.outputs.BRANCH_NAME }}
          title: "[Sync Bot] sync repoqa results"
          body: "Automatically updated RepoQA results"
          base: main
