name: Sync Results
on:
  push:
    branches:
      - main

jobs:
  evalperf-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Sync EvalPerf Results
        run: |
          python results/evalperf/stats.py
      - name: Check Whether Changes Exist
        id: changes
        run: |
          changes=$(git status --porcelain)
          echo "changes=$changes" >> $GITHUB_OUTPUT
      - name: Setup Sync Branch
        id: vars
        run: |
          branch-name="sync-$(date +'%Y-%m-%d-%H-%M-%S')"
          echo "branch-name=$branch-name" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        if ${{ steps.changes.outputs.changes }}
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ steps.push-changes.outputs.BRANCH_NAME }}
          title: "[Sync Bot] sync evalperf results"
          body: "Automatically sync EvaPerf results"
          base: main
